### ISSUE TITLE
Definición pruebas resta

### ISSUE THREAD

**Issue by tiznajo** [G5-MP0487-Edix/AE-3.Activities#11]
<html><body>

Nombre del test | Argumentos | Resultado esperado
-- | -- | --
Resta_de_reales | (a = 1, b = 1) (a = 3, b = 1.2) (a = 10, b = 1.5) | (r=0) (r=1.8) (r=7.5)
Resta_de_enteros | (a = 1, b = 1) (a = 3, b = 2) (a = 10, b = 0) | (r=0) (r=1) (r=-10)
Resta_de_3_números_enteros | (a = 1, b = 1, c = 5) (a = 10, b = 1, c = 1) (a = 5, b = 1, c = 5) | (r=5) (r=8) (r=1)
Resta_con_valor_acumulado | (a = 1, b = 1, c=4) (a = 9, b = 1) (a = 1, b = 1, c = 1,d = 1) | (Cuando se resta la secuencia 1-1-4 r=-4) (Cuando se resta la secuencia 9-1 r=9) (Cuando se resta la secuencia 1-1-1-1 r=-2)

<p dir="auto">Notación:</p>
<ul dir="auto">
<li>a: Valor 1</li>
<li>b: valor 2</li>
<li>c: valor 3</li>
<li>c: valor 4</li>
<li>r: Resultado</li>
</ul>
</body>
</html>

**Comment by aseguragonzalez** [comment]
Revisaría 2 detalles:
1. El caso de uso 4, la resta acumulada, haría referencia a qué métodos estamos probando y como, por ejemplo: <<_Cuando se resta la secuencia 2 y 2 (resta acumulada), obtener acumulado debe ser -4._ >>
2. Resumiría los casos de prueba en una tabla indicando:
   - Nombre del test
   - Parámetros de entrada
   - Resultado esperado

**Comment by tiznajo** [comment]
Listo!!
