### ISSUE TITLE
Definición pruebas suma

### ISSUE THREAD

**Issue by mncaseny** [G5-MP0487-Edix/AE-3.Activities#12]
Identificar los casos de prueba
Ejemplo:

<table>
<tr>
<th>Nombre del test</th><th>Argumentos</th><th>Resultado esperado</th><th>Descripción</th>
</tr>
<tr>
<td>Debe_sumar_dos_numeros_reales</td><td>a=1, b=1.5</td><td>r=2.5</td><td>Método de prueba que testea la suma de dos números reales. </td>
</tr>
<tr>
<td>Debe_sumar_dos_numeros_enteros</td><td>a=1, b=2</td><td>r=3</td><td>Método de prueba que testea la suma de dos números enteros.</td>
</tr>
<tr>
<td>Debe_sumar_tres_numeros_reales</td><td>a=1.5, b=1.5, c=1.5</td><td>r=4.5</td><td>Método de prueba que testea la suma de tres números reales.</td>
</tr>
<tr>
<td>Debe_sumar_el_acumulado</td><td>acumulado=0, b=1</td><td>r=1</td><td>Método de prueba donde testeamos el acumulado, mediante la introducción de un parámetro que se suma al atributo acumulado.</td>
</tr>
<tr>
<td colspan=4>
**Notación**

a: Sumando
b: Sumando
c: Sumando
r: Resultado
acumulado: Acumulador
</td></tr>
</table>

**Comment by aseguragonzalez** [comment]
Revisaría 2 detalles:
1. El caso de uso 4, la suma acumulada, haría referencia a qué métodos estamos probando y como, por ejemplo: <<_Cuando se suma la secuencia 2 y 2 (suma acumulada), obtener acumulado debe ser 4._ >>
2. Resumiría los casos de prueba en una tabla indicando:
   - Nombre del test
   - Parámetros de entrada
   - Resultado esperado

**Comment by mncaseny** [comment]
Perfecto, procedo a cambiarlo.
Muchas gracias.
